<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your password is invalid</name>
   <tag></tag>
   <elementGuidId>792f91a7-a050-4981-9420-3c657fafe5fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flash']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25819a16-877b-44e5-a204-3bf75a03de8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flash</value>
      <webElementGuid>16437f43-a6ad-4cb8-b437-477bfa1b0bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flash error</value>
      <webElementGuid>45747c2d-7431-4393-b25b-d21a268b98b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Your password is invalid!
            ×
          </value>
      <webElementGuid>f0377030-ab11-467d-855c-d22da17ab77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flash&quot;)</value>
      <webElementGuid>55645d88-bc77-4988-806b-35e4f5be1609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flash']</value>
      <webElementGuid>c88f7daf-6986-42ee-83a5-189dccdd4544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flash-messages']/div</value>
      <webElementGuid>250331c1-9bb8-4e3a-9eeb-3be4c1ff2808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Page'])[1]/preceding::div[1]</value>
      <webElementGuid>cba29012-8b8e-4c3f-a1e1-95c36e7811f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tomsmith'])[1]/preceding::div[1]</value>
      <webElementGuid>020d252d-819b-4b0b-8f51-d52f4a6c973f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your password is invalid!']/parent::*</value>
      <webElementGuid>d846e39d-d16e-406d-be88-0dd55ecff016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>b6e7951a-92f2-4feb-b11c-dbcb3bda0350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flash' and (text() = '
            Your password is invalid!
            ×
          ' or . = '
            Your password is invalid!
            ×
          ')]</value>
      <webElementGuid>9bdd5bab-9d0f-4c47-8494-024dbe3c6847</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
